Update php version, phpunit version and fix related problems
codecov/example-php pull request #12
Opened 2019-01-15 09:53 UTC by juffalow

I had several problems with new version of PHPUnit. After these changes, everything is working for me.

2019-03-31 18:19 UTC, peter279k requested changes
It looks good to me, and some stuffs I mention should be concerned.

2019-03-31 18:19 UTC, peter279k commented on .travis.yml
> +    - 7.2
The `php-7.1` is stable. 

I think we should add the `php-7.1` version in Travis CI build.

2019-03-31 18:19 UTC, peter279k commented on composer.json
> +        "php": "^7.2"
I think this should be `^7.1` definition in `composer.json`.

2019-05-31 19:21 UTC, peter279k commented
@juffalow, could you concern about my request changes if possible?

2019-05-31 20:16 UTC, juffalow commented
I updated those things but now the tests are failing. I checked *PHP Supported Versions* and version `7.1`had active support until 1 Dec 2018. Is it necessary to include it?

2019-06-01 03:47 UTC, peter279k commented
> I updated those things but now the tests are failing. I checked _PHP Supported Versions_ and version `7.1`had active support until 1 Dec 2018. Is it necessary to include it?

@juffalow, you're right. We can remove the `php-7.1` at this moment.

But I just notice that the `php-7.1` will have the security support until 1 Dec 2019.

2019-06-02 17:27 UTC, juffalow commented
What do you suggest? Should I take back just the last commit, or solve the problems with `7.1`?

2019-06-02 17:31 UTC, peter279k commented
> What do you suggest? Should I take back just the last commit, or solve the problems with `7.1`?

The `php-7.1` has very soon to be unsupported. I think it's fine to drop `php-7.1` version.

Just take back to last commit I think.

Just notice that this is about the community review, the final decision should be up to this repo owner.

2020-09-09 20:47 UTC, thomasrockhu commented
Closing out as a result of https://github.com/codecov/example-php/commit/688d9f970c63de17fcca4db6421f45a55b7a615a#diff-354f30a63fb0907d4ad57269548329e3. Feel free to reopen if this is still relevant.

2020-09-09 20:47 UTC, closed without merging