Update README.md
codecov/example-php pull request #7
Opened 2018-01-11 21:20 UTC by TomPed

Any more FAQs? or caveats?

2018-10-15 07:25 UTC, jskarpe commented on README.md
> +    - vendor/bin/phpunit --coverage-clover=coverage.xml
`--coverage-clover coverage.xml`

2019-02-25 10:38 UTC, owenvoke requested changes

2019-02-25 10:38 UTC, pxgamer commented on README.md
> +[4]: https://github.com/codecov/codecov-python
This can be removed I guess as it's not used anywhere.

2020-08-04 22:44 UTC, thomasrockhu commented
Closed as a result of https://github.com/codecov/example-php/commit/a39d730ce20a3ba6374960819702bdba5ad6d9bd

2020-08-04 22:44 UTC, closed without merging